/*
 * settings.h
 *
 *  Created on: Dec 18, 2024
 *      Author: Gerry Geyer
 */

#ifndef INC_SETTINGS_H_
#define INC_SETTINGS_H_

#include <parameter.h>

#define DEBUG_MODE ON
//#define DEBUG_MODE OFF

#define SYSTEM DRONE
//#define SYSTEM IMU
//#define SYSTEM FRAME



//#define LOOP_EXERCISE			OFF
//#define LOOP_EXERCISE			LOG_DATA   // Remember to uncomment MX_SDMMC1_SD_Init(); and MX_FATFS_Init();
#define LOOP_EXERCISE			SOLVE_COST_FCT

#define COMMUNICATION_MOTOR		ON
#define COMMUNICATION_IMU_MAG	ON
#define COMMUNICATION_OPT_FLW	ON


#define OFFSET_CALIB_IMU		ON


#define ATTITUDE_CONTROL 		ATT_LQR_CONTROL
//#define ATTITUDE_CONTROL		ATT_P2_CONTROL

#define POSITION_CONTROL		ON

#define SENSORFUSION_METHODE	SF_MADGWICK
//#define SENSORFUSION_METHODE	SF_COMPLEMENTARY
//#define SENSORFUSION_METHODE	SF_EKF
//#define SENSORFUSION_METHODE	SF_AXIS_ALIGN
//#define SENSORFUSION_METHODE	SF_COMPARE_ALL
//#define SENSORFUSION_METHODE	LOG_DATA_ONLY

#define ADAPTIVE_MADGWICK		OFF

#define PREFILTER_SF			OFF
#define POSTFILTER_ATT			OFF

#define PREF_METHODE			IIR
//#define PREF_METHODE			BUTTERWORTH

// ##### SAFTY FUNCTION #######
#define SAFTY_MAX_ANGLE_POS		ON	// Limit the output angle of Position control
#define SAFTY_GROUND_LIMITATION	ON	// Stop the drone if hight angle are detected
#define SAFETY_MOTOR_COMMAND	ON

#define LQR_OUTPUT_RANGE		SCALEQ13 // Position control
//#define LQR_OUTPUT_RANGE		SCALEQ10 // Attitude control


#define TEST_FUNCTION STEP_FUNCTION
//#define TEST_FUNCTION RAMP_FUNCTION
//#define TEST_FUNCTION UP_DOWN_FUNCTION

#define SET_YAW_TO_ZERO			OFF

#define TEST_STATION_ENCODER 	ON
//#define TEST_STATION_ENCODER 	OFF
//#define TEST_STATION_ENCODER_SIGN	POSITIV
#define TEST_STATION_ENCODER_SIGN	NEGATIV


#define OPTICAL_FLOW_GYRO_CORR	ON

#define POS_LQR_USE_INTEGRAL	OFF
#define POS_LQR_INT_ONLY_HIGHT	ON
#define USE_ACC_IF_OPTFL_IS_NOT_GOOD	OFF


#endif /* INC_SETTINGS_H_ */
