/*
 * settings.h
 *
 *  Created on: Dec 18, 2024
 *      Author: Gerry Geyer
 */

#ifndef INC_SETTINGS_H_
#define INC_SETTINGS_H_

#include <parameter.h>

#define DEBUG_MODE ON
//#define DEBUG_MODE OFF




#define LOG_DATA				OFF

#define COMMUNICATION_MOTOR		ON
#define COMMUNICATION_IMU_MAG	ON



//#define ATTITUDE_CONTROL ATT_LQR_CONTROL
#define ATTITUDE_CONTROL		ATT_P2_CONTROL


#define SENSORFUSION_METHODE	SF_MADGWICK
//#define SENSORFUSION_METHODE	SF_COMPLEMENTARY
//#define SENSORFUSION_METHODE	SF_EKF



//#define TEST_FUNCTION STEP_FUNCTION
//#define TEST_FUNCTION RAMP_FUNCTION
#define TEST_FUNCTION UP_DOWN_FUNCTION



#endif /* INC_SETTINGS_H_ */
